title: "Speedster"
description: "A speed testing Mac app that doesn't collect your data"
tagline: "A speed testing Mac app that doesn't collect your test data"
keywords: [osx, mac, internet, speedtest, ookla, speedofme, testspeed]
author:
  name: "Reda Lemeden"
source: source
baseurl: ""
url: https://speedsterapp.com
domain: speedsterapp.com
future: false
show_drafts: false
limit_posts: 0
gems:
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
lsi: true
permalink: pretty

exclude: [
  "bower.json",
  "node_modules",
  "gulpfile.js",
  "package.json",
  "README.md",
  "Gemfile",
  "Gemfile.lock"
]

keep_files: [
  "css",
  "scripts"
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
